### ISSUE TITLE
Update to latest nightly build

### ISSUE THREAD

**Issue by catalinnnn** [robinmoussu/cargo-callgraph#7]
It would be nice having this compatible with channel = "nightly-2021-07-25". Do you plan on doing this?

**Comment by robinmoussu** [comment]
Unfortunately it is too much work, so I don’t think I will do it. I may re-start this project in the future, now that I have a better understanding of the domain space. If I re-start it, there is a high chance that I will not base it on rustc internals. Things change too fast without any migration guide (this isn’t a critic, having quick changes to rustc is more important that being able to support project like this one, at least at this point in time), so I think that it was a bad choice to not start from what rust-analyser is using internally (I think the interfaces are more stable). And I really need to take the time to write a retrospective.

**Comment by catalinnnn** [comment]
Sure. Thanks for the reply :)
